apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-server
  namespace: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus-server
  template:
    metadata:
      labels:
        app: nexus-server
    spec:
      initContainers:
        - name: chown-nexusdata-owner-to-nexus
          image: busybox:1.34.1
          command: [ "/bin/sh","-c" ]
          args: [ "chown -R 200:200 /nexus-data" ]
          volumeMounts:
            - name: pv-nexus-storage
              mountPath: /nexus-data
      securityContext:
        fsGroup: 200
      nodeSelector:
        nexus: "true"
      containers:
        - name: nexus
          image: sonatype/nexus3:3.42.0
          resources:
            limits:
              memory: "8Gi"
              cpu: "1000m"
            requests:
              memory: "4Gi"
              cpu: "700m"
          ports:
            - containerPort: 8081
            - containerPort: 8082
            - containerPort: 8083
            - containerPort: 8084
          volumeMounts:
            - mountPath: /nexus-data
              name: pv-nexus-storage
            - mountPath: /opt/sonatype/sonatype-work
              name: pv-nexus-storage
      volumes:
      - name: pv-nexus-storage
        persistentVolumeClaim:
          claimName: task-pv-claim-nexus
