apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-nexus
  namespace: nexus
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 140Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /app/nexus-storage/nexus-data
