apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim-nexus
  namespace: nexus
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 120Gi
