apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: nexus
spec:
  selector: 
    app: nexus-server
  type: LoadBalancer  
  ports:
    - name: maven-port
      port: 8081
      targetPort: 8081
      nodePort: 31001
    - name: docker-port-proxy
      port: 8082
      targetPort: 8082
      nodePort: 31002
    - name: docker-port-hosted
      port: 8083
      targetPort: 8083
      nodePort: 31003
    - name: docker-port-hosted-ssl
      port: 8084
      targetPort: 8084
      nodePort: 31004
