apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cache
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-cache
  template:
    metadata:
      labels:
        app: nginx-cache
    spec:
      containers:
        - name: jetty-nginx-build-cache
          image: jettyproject/jetty-nginx-build-cache:28-08-2023-10-29
          resources:
            limits:
              memory: "3Gi"
              cpu: "500m"
            requests:
              memory: "2Gi"
              cpu: "400m"
          ports:
            - containerPort: 80
#          env:
#            - name: USERNAME
#              value: admin
#            - name: PASSWORD
#              value: webdav
