apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-master
  namespace: jenkins-master
spec:
  replicas: 1
  selector:
    matchLabels:
      jenkins: master
  template:
    metadata:
      labels:
        jenkins: master
    spec:
      securityContext:
        fsGroup: 114
        runAsUser: 111
      serviceAccountName: jenkins-admin
      containers:
        - name: jenkins
          image: jenkins/jenkins:2.377-jdk17
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - name: httpport
              containerPort: 8080
            - name: jnlpport
              containerPort: 7777
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home/
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: task-pv-claim-jenkins