apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-master
  namespace: jenkins-master
spec:
  replicas: 1
  selector:
    matchLabels:
      jenkins: master
  template:
    metadata:
      labels:
        app: jenkins-server
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      serviceAccountName: jenkins-admin
      containers:
        - name: jenkins
          image: jenkins/jenkins:2.378-jdk17
          env:
            - name: JENKINS_JAVA_OPTS
              value: -Djava.awt.headless=true -Dblueocean.collectRuns.threads=90 -Xmx28g -Xms12g -server -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+ExplicitGCInvokesConcurrent -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:+UseStringDeduplication -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.LAUNCH_DIAGNOSTICS=true
          resources:
            limits:
              memory: "30Gi"
              cpu: "6"
            requests:
              memory: "20Gi"
              cpu: "4"
          ports:
            - name: httpport
              containerPort: 8080
            - name: jnlpport
              containerPort: 7777
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home/
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: task-pv-claim-jenkins
