apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim-jenkins
  namespace: jenkins-master
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-jenkins
  namespace: jenkins-master
  labels:
    jenkins: master
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 400Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/jenkins/

