apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cache
  namespace: jenkins
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: ngnix
          image: nginx:1.23.3
          resources:
            limits:
              memory: "3Gi"
              cpu: "500m"
            requests:
              memory: "2Gi"
              cpu: "400m"
